version: '3.8'
services:
  my-project:
    container_name: my-project
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - '3000:3000'
    environment:
      CORS_ORIGIN: "*"
