version: '3.8'
services:
  ms-api:
    container_name: ms-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - '2222:3000'
    environment:
      CORS_ORIGIN: "*"
    networks:
      - ms-network

networks:
  ms-network:
    name: MS
    driver: bridge
