name: Build Node Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-node-action
          ref: 1.0.1
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-node-action

      - name: Run action
        uses: './build-node-action/application/github'
